name: Artifacts CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Build Artifacts
      run: |
        cd kedro-solution/src
        pip install -r requirements.txt
        cd ..
        kedro run
        cp mlflowModel.pkl ../webapp/src/mlflowModel.pkl
    - name: Commit artifacts
      run: |
        git config --global user.name 'BuildBot_Baggins'
        git config --global user.email 'buildbot@users.noreply.github.com'
        git add --all
        git commit -am "Automated artifact commit"
        git push
    - name: Publish mlflow image to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: kappi43/asi-mlflow:test
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: kedro-solution/Dockerfile-mlflow
    - name: Publish kedro viz image to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: kappi43/asi-kedro-viz:test
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: kedro-solution/Dockerfile-kedro-viz
    - name: Publish web app image to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: kappi43/asi-webapp:test
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: webapp/Dockerfile
#    - name: Google Auth
#      uses: google-github-actions/auth@v1
#      with:
#        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
#    - name: Cloud deploy mlflow
#      uses: google-github-actions/deploy-cloudrun@v1
#      with:
#        service: asi-mlflow
#        region: europe-west1
#        image: kappi43/asi-mlflow:test
#    - name: Cloud deploy kedro-viz
#      uses: google-github-actions/deploy-cloudrun@v1
#      with:
#        service: asi-kedro-viz
#        region: europe-west1
#        image: kappi43/asi-kedro-viz:test
#    - name: Cloud deploy webapp
#      uses: google-github-actions/deploy-cloudrun@v1
#      with:
#        service: asi-webapp
#        region: europe-west1
#        image: kappi43/asi-webapp:test