name: Artifacts CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: |
        cd kedro-solution/src
        pip install -r requirements.txt
        cd ..
        kedro run
        cp mlflowModel.pkl ../webapp/src/mlflowModel.pkl
    - name: Commit artifacts
      run: |
        git config --global user.name 'BuildBot_Baggins'
        git config --global user.email 'buildbot@users.noreply.github.com'
        git commit -am "Automated artifact commit"
        git push
    - name: Publish mlflow image to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: kappi43/asi-mlflow:test
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: kedro-solution/Dockerfile-mlflow
    - name: Publish kedro viz image to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: kappi43/asi-kedro-viz:test
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: kedro-solution/Dockerfile-kedro-viz
