name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Publish mlflow image to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: kappi43/asi-mlflow:test
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: kedro-solution/Dockerfile-mlflow
    - name: Publish kedro viz image to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: kappi43/asi-kedro-viz:test
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: kedro-solution/Dockerfile-kedro-viz
